homeassistant:
  # Name of the location where Home Assistant is running
  name: Thuis
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 6
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/tmp
# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_named themes
# Enables configuration UI
config:
hassio:
system_health:
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
  api_password: !secret http_password
  cors_allowed_origins:
    - http://192.168.0.119:7080
    - http://192.168.0.119:1880

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:
#  ignore: 
#    - harmony
#    - philips_hue
#    - sonos
#    - samsung_tv
    
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction

    
#  - platform: ring
ring:
  username: !secret ring_user
  password: !secret ring_password
  
binary_sensor: !include binary_sensor.yaml
# Text to speech  
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
  
zigbee2mqtt_networkmap:
  
panel_iframe:
  networkmap:
     title: 'Zigbee Map'
     url: '/local/zigbee2mqtt_networkmap/map.html'
     icon: 'mdi:graphql'
#  configurator:
#    title: Configurator
#    icon: mdi:wrench
#    url: http://192.168.0.119:3218
  tvheadend:
    title: tvheadend
    url: http://192.168.0.9:9981
    icon: mdi:television-box
  mdiindex:
    title: node-red
    url: http://192.168.0.196:1880
    
zwave:
  usb_path: /dev/ttyACM0
  
weather:
  - platform: buienradar
    name: 'Thuis'
    # Force 'Meetstation Volkel' to be used:
    latitude: !secret latitude
    longitude: !secret longitude
    forecast: True
  
remote:
  - platform: harmony
    name: Harmony Woonkamer
    host: 192.168.0.4
  - platform: harmony
    name: Harmony Slaapkamer
    host: 192.168.0.30
  
input_select: !include input_select.yaml
      
sabnzbd:
  api_key: !secret sabnzbd_password
  host: 192.168.0.114
  name: sab
  port: 8085
  ssl: false
  
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size
    
camera: !include camera.yaml
    
ffmpeg:

sensor: !include sensor.yaml
logger:
  default: warn
#  logs:
#    homeassistant.components.device_tracker: debug
#    homeassistant.components.camera: critical
    
    
media_player: !include media_player.yaml
device_tracker:
  - platform: tile
    username: !secret email_user
    password: !secret tile_password
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    prefix: life360
    show_as_state: driving, moving, places
    driving_speed: 18
    max_gps_accuracy: 200
    max_update_wait:
      minutes: 45
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    home_interval: 10
    interval_seconds: 30

#influxdb:
#  host: 192.168.0.119
#  database: home_assistant
#  username: !secret influxdb_user
#  password: !secret influxdb_password  
    
recorder:
  db_url: !secret mysql
  purge_keep_days: 7
  purge_interval: 7

input_boolean: !include input_boolean.yaml
    
#history_graph:
#  stroomverbruik:
#    entities:
##      - sensor.solaredge_currentpower
#      - sensor.p1_inkoopnu
#    hours_to_show: 24
#    refresh: 60
#    name: Stroom
    
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
ifttt:
  key: !secret ifttt_key
  
# Example configuration.yaml entry for the notifier
notify:
  - platform: html5
    name: Html5
    gcm_api_key: !secret html5_gcm_api_key
    gcm_sender_id: !secret html5_gcm_sender_id
#  - name: Huis Bot
#    platform: telegram
#    chat_id: 190764106
    
input_number: !include input_number.yaml

  
input_datetime:
  tijdbuitenlampaan:
    name: Buiten lamp aan
    has_date: false
    has_time: true
  tijdbuitenlampuit:
    name: Buiten lamp uit
    has_date: false
    has_time: true
    
#hue:
#  bridges:
#    - host: 192.168.0.33
#      allow_unreachable: true
      
mqtt:
  broker: 192.168.0.196
  username: !secret mqtt_user
  password: !secret mqtt_password
  
tado:
  username: !secret tado_user
  password: !secret tado_password
  
light: !include lights.yaml
switch: !include switch.yaml
cast:
  media_player:
  - host: 192.168.0.26
  - host: 192.168.0.25
  - host: 192.168.0.27
googlehome:
  devices:
  - host: 192.168.0.31
  - host: 192.168.0.25
  - host: 192.168.0.139
timer:
  zigbee_permit_join:
    name: tijd nog
    duration: 600 # Updated this to the number of seconds you wish

google_assistant: !include google_assistant.yaml


scene: !include scene.yaml
custom_updater:
  show_installable: true
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/awesome-developer/my-awesome-repo/master/custom_cards.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/allow-updates/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json
    
zone:
  - name: Werk Tarik
    latitude: !secret Werk_Tarik_latitude
    longitude: !secret Werk_Tarik_longitude
    radius: 250

  - name: Mama Tarik
    latitude: !secret Mama_Tarik_latitude
    longitude: !secret Mama_Tarik_longitude
    radius: 250

  - name: Werk Houda
    latitude: !secret Werk_Houda_latitude
    longitude: !secret Werk_Houda_longitude
    radius: 250
